version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "yum install -y jq >/dev/null 2>&1 || true"
      - "aws --version"
  build:
    commands:
      - "echo '=== Start CodeGuru review ==='"
      - >
        REVIEW_ARN=$(aws codeguru-reviewer create-code-review
        --name pipeline-review-$(date +%s)
        --repository-association-arn "${CODEGURU_ASSOCIATION_ARN}"
        --type "RepositoryAnalysis={RepositoryHead={BranchName=${BRANCH}}}"
        --query 'CodeReview.CodeReviewArn' --output text)
      - "echo ReviewARN=${REVIEW_ARN}"
      - |
        for i in {1..20}; do
          STATUS=$(aws codeguru-reviewer describe-code-review \
            --code-review-arn "$REVIEW_ARN" \
            --query 'CodeReview.State' --output text)
          echo "Status: $STATUS (attempt $i/20)"
          [ "$STATUS" = "Completed" ] && break
          [ "$STATUS" = "Failed" ] && echo 'CodeGuru review failed' && exit 1
          sleep 15
        done
      - "aws codeguru-reviewer describe-code-review --code-review-arn \"$REVIEW_ARN\" --query 'CodeReview.Metrics' --output json > review-metrics.json"
      - "aws codeguru-reviewer list-recommendations --code-review-arn \"$REVIEW_ARN\" --output json > review-output.json"
artifacts:
  files:
    - review-output.json
    - review-metrics.json
